language: python
python:
  - "3.9"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - python -m unittest
before_deploy:
  - poetry config respositories.testpypi https://test.pypi.org/legacy/
  - poetry config http-basic.testpypi $PYPI_USER $PYPI_PASS
  - poetry build
deploy:
  provider: script
  script: poetry publish -r testpypi
  on:
    branch: main
